# -*- coding: utf-8 -*-

from collections import namedtuple


OCCUPATIONS = namedtuple('OCCUPATIONS', ['WARRIOR', 'DRUID', 'MAGE', 'PRIEST', 'ROGUE', 'WARLOCK', 'HUNTER', 'PALADIN'])\
    ('Warrior', 'Druid', 'Mage', 'Priest', 'Rogue', 'Warlock', 'Hunter', 'Paladin')


TANK_OCCUPATIONS = [OCCUPATIONS.WARRIOR, OCCUPATIONS.DRUID]
AD_OCCUPATIONS = [OCCUPATIONS.ROGUE, OCCUPATIONS.WARRIOR, OCCUPATIONS.HUNTER]
AP_OCCUPATIONS = [OCCUPATIONS.MAGE, OCCUPATIONS.WARLOCK]
HEALER_OCCUPATIONS = [OCCUPATIONS.PRIEST, OCCUPATIONS.PALADIN, OCCUPATIONS.DRUID]# -*- coding: utf-8 -*-